module.exports = {
  customColsCol: 'js-grid-customcols-col',
  gridCellHeadingOrderable: 'js-grid-cell-heading-orderable',
  formCreateCell: 'js-form-create-cell',
  selected: 'is-selected',
  reading: 'is-reading',
  cellHeading: 'js-grid-cell-heading',
  table: 'js-grid-table',
  tableContainer: 'js-grid-table-container',
  row: 'js-grid-row',
  rowHeading: 'js-grid-row-heading',
  cell: 'js-grid-cell',
  input: 'js-grid-cell-input',
  searchField: 'js-grid-search-field',
  searchInput: 'js-grid-search-input',
  searchSelect: 'js-grid-search-select',
  pageSelect: 'js-grid-pagination-select',
  perPageSelect: 'js-grid-cell-input-perpage',
  pageContainer: 'js-grid-pagination-container',
  buttonRemoveFilters: 'js-grid-button-remove-filters',
  spinner: 'js-grid-spinner',
  buttonDelete: 'js-grid-row-button-delete',
  buttonCreate: 'js-grid-button-create',
  noResults: 'js-grid-no-rows'
}
